export interface Country {
  name: string;
  iso: string;
  code: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", iso: "AF", code: "+93", flag: "🇦🇫" },
  { name: "Albania", iso: "AL", code: "+355", flag: "🇦🇱" },
  { name: "Algeria", iso: "DZ", code: "+213", flag: "🇩🇿" },
  { name: "Andorra", iso: "AD", code: "+376", flag: "🇦🇩" },
  { name: "Angola", iso: "AO", code: "+244", flag: "🇦🇴" },
  { name: "Argentina", iso: "AR", code: "+54", flag: "🇦🇷" },
  { name: "Armenia", iso: "AM", code: "+374", flag: "🇦🇲" },
  { name: "Australia", iso: "AU", code: "+61", flag: "🇦🇺" },
  { name: "Austria", iso: "AT", code: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", iso: "AZ", code: "+994", flag: "🇦🇿" },
  { name: "Bahrain", iso: "BH", code: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", iso: "BD", code: "+880", flag: "🇧🇩" },
  { name: "Belarus", iso: "BY", code: "+375", flag: "🇧🇾" },
  { name: "Belgium", iso: "BE", code: "+32", flag: "🇧🇪" },
  { name: "Bhutan", iso: "BT", code: "+975", flag: "🇧🇹" },
  { name: "Bolivia", iso: "BO", code: "+591", flag: "🇧🇴" },
  { name: "Bosnia & Herzegovina", iso: "BA", code: "+387", flag: "🇧🇦" },
  { name: "Brazil", iso: "BR", code: "+55", flag: "🇧🇷" },
  { name: "Brunei", iso: "BN", code: "+673", flag: "🇧🇳" },
  { name: "Bulgaria", iso: "BG", code: "+359", flag: "🇧🇬" },
  { name: "Cambodia", iso: "KH", code: "+855", flag: "🇰🇭" },
  { name: "Cameroon", iso: "CM", code: "+237", flag: "🇨🇲" },
  { name: "Canada", iso: "CA", code: "+1", flag: "🇨🇦" },
  { name: "Chile", iso: "CL", code: "+56", flag: "🇨🇱" },
  { name: "China", iso: "CN", code: "+86", flag: "🇨🇳" },
  { name: "Colombia", iso: "CO", code: "+57", flag: "🇨🇴" },
  { name: "Costa Rica", iso: "CR", code: "+506", flag: "🇨🇷" },
  { name: "Croatia", iso: "HR", code: "+385", flag: "🇭🇷" },
  { name: "Cyprus", iso: "CY", code: "+357", flag: "🇨🇾" },
  { name: "Czechia", iso: "CZ", code: "+420", flag: "🇨🇿" },
  { name: "Denmark", iso: "DK", code: "+45", flag: "🇩🇰" },
  { name: "Ecuador", iso: "EC", code: "+593", flag: "🇪🇨" },
  { name: "Egypt", iso: "EG", code: "+20", flag: "🇪🇬" },
  { name: "Estonia", iso: "EE", code: "+372", flag: "🇪🇪" },
  { name: "Ethiopia", iso: "ET", code: "+251", flag: "🇪🇹" },
  { name: "Finland", iso: "FI", code: "+358", flag: "🇫🇮" },
  { name: "France", iso: "FR", code: "+33", flag: "🇫🇷" },
  { name: "Georgia", iso: "GE", code: "+995", flag: "🇬🇪" },
  { name: "Germany", iso: "DE", code: "+49", flag: "🇩🇪" },
  { name: "Ghana", iso: "GH", code: "+233", flag: "🇬🇭" },
  { name: "Greece", iso: "GR", code: "+30", flag: "🇬🇷" },
  { name: "Hong Kong", iso: "HK", code: "+852", flag: "🇭🇰" },
  { name: "Hungary", iso: "HU", code: "+36", flag: "🇭🇺" },
  { name: "Iceland", iso: "IS", code: "+354", flag: "🇮🇸" },
  { name: "India", iso: "IN", code: "+91", flag: "🇮🇳" },
  { name: "Indonesia", iso: "ID", code: "+62", flag: "🇮🇩" },
  { name: "Iran", iso: "IR", code: "+98", flag: "🇮🇷" },
  { name: "Iraq", iso: "IQ", code: "+964", flag: "🇮🇶" },
  { name: "Ireland", iso: "IE", code: "+353", flag: "🇮🇪" },
  { name: "Israel", iso: "IL", code: "+972", flag: "🇮🇱" },
  { name: "Italy", iso: "IT", code: "+39", flag: "🇮🇹" },
  { name: "Japan", iso: "JP", code: "+81", flag: "🇯🇵" },
  { name: "Jordan", iso: "JO", code: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", iso: "KZ", code: "+7", flag: "🇰🇿" },
  { name: "Kenya", iso: "KE", code: "+254", flag: "🇰🇪" },
  { name: "Kuwait", iso: "KW", code: "+965", flag: "🇰🇼" },
  { name: "Kyrgyzstan", iso: "KG", code: "+996", flag: "🇰🇬" },
  { name: "Laos", iso: "LA", code: "+856", flag: "🇱🇦" },
  { name: "Latvia", iso: "LV", code: "+371", flag: "🇱🇻" },
  { name: "Lebanon", iso: "LB", code: "+961", flag: "🇱🇧" },
  { name: "Libya", iso: "LY", code: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", iso: "LI", code: "+423", flag: "🇱🇮" },
  { name: "Lithuania", iso: "LT", code: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", iso: "LU", code: "+352", flag: "🇱🇺" },
  { name: "Macao", iso: "MO", code: "+853", flag: "🇲🇴" },
  { name: "Malaysia", iso: "MY", code: "+60", flag: "🇲🇾" },
  { name: "Maldives", iso: "MV", code: "+960", flag: "🇲🇻" },
  { name: "Malta", iso: "MT", code: "+356", flag: "🇲🇹" },
  { name: "Mauritius", iso: "MU", code: "+230", flag: "🇲🇺" },
  { name: "Mexico", iso: "MX", code: "+52", flag: "🇲🇽" },
  { name: "Moldova", iso: "MD", code: "+373", flag: "🇲🇩" },
  { name: "Monaco", iso: "MC", code: "+377", flag: "🇲🇨" },
  { name: "Mongolia", iso: "MN", code: "+976", flag: "🇲🇳" },
  { name: "Montenegro", iso: "ME", code: "+382", flag: "🇲🇪" },
  { name: "Morocco", iso: "MA", code: "+212", flag: "🇲🇦" },
  { name: "Myanmar", iso: "MM", code: "+95", flag: "🇲🇲" },
  { name: "Nepal", iso: "NP", code: "+977", flag: "🇳🇵" },
  { name: "Netherlands", iso: "NL", code: "+31", flag: "🇳🇱" },
  { name: "New Zealand", iso: "NZ", code: "+64", flag: "🇳🇿" },
  { name: "Nigeria", iso: "NG", code: "+234", flag: "🇳🇬" },
  { name: "North Macedonia", iso: "MK", code: "+389", flag: "🇲🇰" },
  { name: "Norway", iso: "NO", code: "+47", flag: "🇳🇴" },
  { name: "Oman", iso: "OM", code: "+968", flag: "🇴🇲" },
  { name: "Pakistan", iso: "PK", code: "+92", flag: "🇵🇰" },
  { name: "Panama", iso: "PA", code: "+507", flag: "🇵🇦" },
  { name: "Paraguay", iso: "PY", code: "+595", flag: "🇵🇾" },
  { name: "Peru", iso: "PE", code: "+51", flag: "🇵🇪" },
  { name: "Philippines", iso: "PH", code: "+63", flag: "🇵🇭" },
  { name: "Poland", iso: "PL", code: "+48", flag: "🇵🇱" },
  { name: "Portugal", iso: "PT", code: "+351", flag: "🇵🇹" },
  { name: "Qatar", iso: "QA", code: "+974", flag: "🇶🇦" },
  { name: "Romania", iso: "RO", code: "+40", flag: "🇷🇴" },
  { name: "Russia", iso: "RU", code: "+7", flag: "🇷🇺" },
  { name: "Saudi Arabia", iso: "SA", code: "+966", flag: "🇸🇦" },
  { name: "Serbia", iso: "RS", code: "+381", flag: "🇷🇸" },
  { name: "Singapore", iso: "SG", code: "+65", flag: "🇸🇬" },
  { name: "Slovakia", iso: "SK", code: "+421", flag: "🇸🇰" },
  { name: "Slovenia", iso: "SI", code: "+386", flag: "🇸🇮" },
  { name: "South Africa", iso: "ZA", code: "+27", flag: "🇿🇦" },
  { name: "South Korea", iso: "KR", code: "+82", flag: "🇰🇷" },
  { name: "Spain", iso: "ES", code: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", iso: "LK", code: "+94", flag: "🇱🇰" },
  { name: "Sweden", iso: "SE", code: "+46", flag: "🇸🇪" },
  { name: "Switzerland", iso: "CH", code: "+41", flag: "🇨🇭" },
  { name: "Taiwan", iso: "TW", code: "+886", flag: "🇹🇼" },
  { name: "Tajikistan", iso: "TJ", code: "+992", flag: "🇹🇯" },
  { name: "Thailand", iso: "TH", code: "+66", flag: "🇹🇭" },
  { name: "Turkey", iso: "TR", code: "+90", flag: "🇹🇷" },
  { name: "Ukraine", iso: "UA", code: "+380", flag: "🇺🇦" },
  { name: "United Arab Emirates", iso: "AE", code: "+971", flag: "🇦🇪" },
  { name: "United Kingdom", iso: "GB", code: "+44", flag: "🇬🇧" },
  { name: "United States", iso: "US", code: "+1", flag: "🇺🇸" },
  { name: "Uruguay", iso: "UY", code: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", iso: "UZ", code: "+998", flag: "🇺🇿" },
  { name: "Venezuela", iso: "VE", code: "+58", flag: "🇻🇪" },
  { name: "Vietnam", iso: "VN", code: "+84", flag: "🇻🇳" },
  { name: "Yemen", iso: "YE", code: "+967", flag: "🇾🇪" },
  { name: "Zimbabwe", iso: "ZW", code: "+263", flag: "🇿🇼" }
];
